export enum VARIANTS {
  SHAPE = 'SHAPE',
  BACKGROUND_COLOR = 'BACKGROUND_COLOR',
  STEM_COLOR = 'STEM_COLOR',
  LEAF_COLOR = 'LEAF_COLOR',
  CHERRY_COLOR = 'CHERRY_COLOR'
}

export enum ORGANIC_COLORS {
  BROWN = 'BROWN',
  LIGHT_GREEN = 'LIGHT_GREEN',
  MID_GREEN = 'MID_GREEN',
  DARK_GREEN = 'DARK_GREEN',
  GREEN_RED = 'GREEN_RED',
  LIGHT_RED = 'LIGHT_RED',
  MID_RED = 'MID_RED',
  DARK_RED = 'DARK_RED'
}

export enum SHAPE_VARIANTS {
  SQUARE = 'square',
  CIRCLE = 'circle',
  HEXAGON = 'hexagon',
  RANDOM = 'random'
}

export enum BACKGROUND_COLORS {
  GREEN = 'GREEN',
  RED = 'RED',
  PINK = 'PINK',
  YELLOW = 'YELLOW',
  BLUE = 'BLUE',
  PURPLE = 'PURPLE'
}

export const mapColor: Record<ORGANIC_COLORS, string> = {
  [ORGANIC_COLORS.BROWN]: '#795548',
  [ORGANIC_COLORS.LIGHT_GREEN]: '#CDDC39',
  [ORGANIC_COLORS.MID_GREEN]: '#8BC34A',
  [ORGANIC_COLORS.DARK_GREEN]: '#388E3C',
  [ORGANIC_COLORS.GREEN_RED]: '#E65100',
  [ORGANIC_COLORS.LIGHT_RED]: '#FF5252',
  [ORGANIC_COLORS.MID_RED]: '#FF1744',
  [ORGANIC_COLORS.DARK_RED]: '#D50000'
};

export const mapBackgroundColor: Record<BACKGROUND_COLORS, string> = {
  [BACKGROUND_COLORS.RED]: '#EF9F8F',
  [BACKGROUND_COLORS.YELLOW]: '#DFEF8F',
  [BACKGROUND_COLORS.GREEN]: '#8FEF9F',
  [BACKGROUND_COLORS.BLUE]: '#8FDFEF',
  [BACKGROUND_COLORS.PURPLE]: '#9F8FEF',
  [BACKGROUND_COLORS.PINK]: '#EF8FDF'
};

export const stemVariants = [
  ORGANIC_COLORS.LIGHT_GREEN,
  ORGANIC_COLORS.MID_GREEN
];

export const leafVariants = [
  ORGANIC_COLORS.LIGHT_GREEN,
  ORGANIC_COLORS.MID_GREEN,
  ORGANIC_COLORS.DARK_GREEN
];

export const shapeVariants = [
  SHAPE_VARIANTS.SQUARE,
  SHAPE_VARIANTS.CIRCLE,
  SHAPE_VARIANTS.HEXAGON,
  SHAPE_VARIANTS.RANDOM
];

export const cherryColorVariants = [
  ['#E3D858', '#9DA434'],
  ['#D1D966', '#E68181'],
  ['#FF1744', '#D50000'],
  ['#97071C', '#4C0101'],
  ['#AF114E', '#7F1060']
];

export const backgroundColorVariants = [
  BACKGROUND_COLORS.RED,
  BACKGROUND_COLORS.YELLOW,
  BACKGROUND_COLORS.GREEN,
  BACKGROUND_COLORS.BLUE,
  BACKGROUND_COLORS.PURPLE,
  BACKGROUND_COLORS.PINK
];
